### ISSUE TITLE
Namespace ScriptableSingleton could not be found.

### ISSUE THREAD

**Issue by purnamasari** [Unity-Technologies/AutoLOD#30]
Hello I come across internet and found this interesting unity tools. I planning to build on PC Standalone by Unity 2018.1.0f2. Everything works fine on editor, but when I build it resulting error:

> Assets/AutoLOD/Scripts/Helpers/MonoBehaviourHelper.cs(15,40): error CS0246: The type or namespace name `ScriptableSingleton' could not be found. Are you missing an assembly reference?

What am I supposed to do to fix this? Trying to add some #if UNITY_EDITOR but doesn't work at all. Thank you.

**Comment by amirebrahimi** [comment]
Fixed with 7959d5f78e3fa722b64f276ddec71953fd0f2378
